# -*- coding: utf-8 -*-
# """Hackerrank.ipynb

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1CkB-eIwyMrb5J5kkgPZydbXhjOKaSmWO

# #IF ELSE
# """

n = int(input("What is yor number?"))

if n%2==0 and (n in range(2,6) or n>20 ): 
    print ("Not Weird") 
else: print ("Weird")

"""#Loop"""

n = int(input("What is yor number?"))

for i in range(1, n+1):
  print(i, end="")

"""#Is a leap year function"""

def is_leap(year):
    
    # Write your logic here
    
    return year%4 == 0 and (year%400 == 0 or year%100 !=0)

year = int(input())
is_leap(year)

"""#List comprehension"""

x = int(input())
y = int(input())
z = int(input())
n = int(input())
    
print([[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1)if sum([i,j,k]) != n])

"""#Find the Runner-Up Score!"""

arr=[1,1,2,3,4,5,5,6,7]

print (sorted(set(arr))[-2])

"""#Nested list"""

if __name__ == '__main__':
    a= []
    for _ in range(int(input())):
        name = input()
        score = float(input())
        a.append([score, name])

    a.sort()
    b = [i for i in a if i[0] != a[0][0]]
    c = [j for j in b if j[0] == b[0][0]]
    
    c.sort(key=lambda x: x[1])
    for i in range(len(c)):
        print(c[i][1])
